version: '2'

services:
  postgres:
    image: 'bitnami/postgresql:latest'
    environment:
      - POSTGRESQL_DATABASE=fastfeet-db
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_POSTGRES_PASSWORD=docker
    ports:
      - '5432:5432'
    volumes:
      - ./data/pg:/data/postgres